#!/bin/sh

LAMANOTES_PORT=${LAMANOTES_PORT:-${FLATNOTES_PORT:-8080}}
LAMANOTES_PATH_PREFIX=${LAMANOTES_PATH_PREFIX:-${FLATNOTES_PATH_PREFIX:-}}
curl -f http://localhost:${LAMANOTES_PORT}${LAMANOTES_PATH_PREFIX}/health || exit 1
